### ISSUE TITLE
What _is_ the "checkout"?

### ISSUE THREAD

**Issue by thesofakillers** [GEM-benchmark/GEM-metrics#101]
Hi, thank you very much for this work.

I'm reading the README as a way of reading docs, and I don't really understand, what is the "checkout" you are referring to? Why would I need access to it?

Thanks

**Comment by tuetschek** [comment]
Hi @thesofakillers by checkout I mean the clone of this repository – I've just changed the wording, hopefully it's clearer now. You'd want access in case you want to edit the source code, e.g. integrate some new metrics.

**Comment by thesofakillers** [comment]
ah understood, thx!
