### ISSUE TITLE
Parameter number as descriptive metric

### ISSUE THREAD

**Issue by sebastianGehrmann** [GEM-benchmark/GEM-metrics#23]
We already ask participants to add a field `param_count` in their submission files. It should be easy to write a function in a metrics wrapper that moves it to the score file so that it can be displayed on the website alongside other descriptive metrics like output_length.

**Comment by evanmiltenburg** [comment]
This sounds like something that is very easy to forget to put in the output file, so there should be a clear error message if `param_count` is missing.

**Comment by tuetschek** [comment]
@evanmiltenburg & @sebastianGehrmann : Would fb5d2620837cbab45e3803a4a77a8d4f465cd654 be what you want? 
* The parameter count is not a metric, but it's added to the output dict when the submission starts processing, next to the submission name. 
* There will be a warning on the output if the parameter count is not present.

**Comment by sebastianGehrmann** [comment]
Yes that implementation looks exactly like what I thought.

**Comment by tuetschek** [comment]
Cool, thanks! Closing it & next time we recompute any scores, the parameter number will be there :-).
