### ISSUE TITLE
Adding WER/TER/CIDEr

### ISSUE THREAD

**Issue by sebastianGehrmann** [GEM-benchmark/GEM-metrics#33]
We could always use more metrics :) 

Here are some python implementations: https://github.com/gcunhase/NLPMetrics

**Comment by tuetschek** [comment]
I think TER is also implemented in SacreBLEU (which we're depending on currently)

**Comment by leoribeiro** [comment]
PR #82 includes TER in the GEM metrics.

**Comment by jordiclive** [comment]
#90, #89  Hopefully we can close

**Comment by tuetschek** [comment]
@jordiclive Yes, thanks for the reminder!
