### ISSUE TITLE
Add NIST

### ISSUE THREAD

**Issue by sebastianGehrmann** [GEM-benchmark/GEM-metrics#35]
I guess you have your own implementation already @tuetschek ?
https://github.com/tuetschek/e2e-metrics#mt-eval

**Comment by tuetschek** [comment]
Yep, it's actually hidden in [code in our repo I used before plugging in SacreBLEU](https://github.com/GEM-benchmark/GEM-metrics/blob/main/gem_metrics/impl/pymteval.py#L203), so this is just a question of plugging it in – shouldn't take long, will look into it.

**Comment by tuetschek** [comment]
Should be done in 917f9d0.
