### ISSUE TITLE
Cannot run meteor evaluation

### ISSUE THREAD

**Issue by lxuechen** [GEM-benchmark/GEM-metrics#53]
I cannot download the data required for meteor evaluation. The following is the error message.
```bash
[W 210731 14:42:32 data:54] <local path> not found -- downloading https://github.com/GEM-benchmark/GEM-metrics/releases/download/data/meteor.tar.gz.
 This may take a few minutes.
[W 210731 14:42:33 meteor:21] Cannot run Meteor -- Skipping: HTTP Error 404: Not Found
```
`<local path>` is redacted.

**Comment by lxuechen** [comment]
I fixed this by manually copying to `<local path>` the content in [this](https://github.com/tuetschek/e2e-metrics/tree/master/pycocoevalcap/meteor) folder. 

This should be the right one, though it'll still be good if we needn't this extra manual step.

**Comment by tuetschek** [comment]
@lxuechen Thanks for noticing! Looks like that file got removed from our list of downloadable files by accident. I added it back, now it should auto-download without any problems. Feel free to reopen if it still doesn't work for you.
