### ISSUE TITLE
Colab or Kaggle compatibility (Python 3.7 usage instead of 3.8)

### ISSUE THREAD

**Issue by asnota** [GEM-benchmark/GEM-metrics#61]
Hello, I've been trying to run the tests on Colab/Kaggle platforms, however the currect installation on those platforms in 3.7.12, whereas the `cached_property` of the `functools` decorator used in text.py file appeared starting from Python 3.8 (https://github.com/python/typeshed/issues/4198#issuecomment-640233038). I therefore keep receiving `AttributeError: module 'functools' has no attribute 'cached_property'` with a simple import statement, which makes this library not usable on these platforms.

**Comment by sebastianGehrmann** [comment]
This should be fixed.
