### ISSUE TITLE
Example on a single metric usage with the input format

### ISSUE THREAD

**Issue by asnota** [GEM-benchmark/GEM-metrics#62]
The expected input format with an example of the metric usage might be useful to add to the docstrings of each of the metrics.

**Comment by tuetschek** [comment]
@asnota would the [current README](https://github.com/GEM-benchmark/GEM-metrics/blob/main/README.md#library-usage) be OK? All metrics should compute the same, so there's probably no need to add this individually.

**Comment by asnota** [comment]
Agree, if it is given as an argument to compute() function, its usage should be straight forward.
