### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by asnota** [GEM-benchmark/GEM-metrics#65]
Following the recent typo correction, I discovered that the tests are failing (https://github.com/asnota/GEM-metrics/runs/3977022201?check_suite_focus=true) with `AttributeError: module 'sacrebleu' has no attribute 'TOKENIZERS'` which is true for `test_metric`, test_metric_identical_pred_ref` and `test_metric_mismatched_pred_ref`  (`(tests.test_sari.TestSari)`) and 3  assertion errors.

**Comment by ndaheim** [comment]
ince the BLEU errors are resolved with pull request #67 and MSTTR errors are tracked in #55 I'll close this one.
